Return-Path: <simonstl@simonstl.com>
X-Original-To: simonstl@simonstl.com
Delivered-To: simonstl@simonstl.com
Received: from SimonMacBook.local (cpe-24-59-184-80.twcny.res.rr.com [24.59.184.80])
	by mail.simonstl.com (Postfix) with ESMTPSA id 5384D18C0031
	for <simonstl@simonstl.com>; Sat, 14 Apr 2012 12:48:30 -0400 (EDT)
Message-ID: <4F89AA5A.4060203@simonstl.com>
Date: Sat, 14 Apr 2012 12:48:26 -0400
From: "Edd Dumbill" <edd@example.org>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:11.0) Gecko/20120327 Thunderbird/11.0.1
MIME-Version: 1.0
To: "Simon St.Laurent" <simonstl@simonstl.com>
Subject: Score
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: 7bit

Student: 1
GPA: 3.34
