From edd@example.org Wed Aug 6 04:29:56 2012
Return-Path: <edd@example.org>
X-Original-To: edd@example.org
Delivered-To: edd@mail.example.org
Received: from [192.168.250.137] (foo.example.org [192.168.250.5])
(using TLSv1 with cipher AES128-SHA (128/128 bits))
(No client certificate requested)
by mail.example.org (Postfix) with ESMTP id C01F3140040
for <edd@example.org>; Wed, 6 Aug 2012 12:32:54 +0100 (BST)
Message-Id: <B3E7FCF0-49E0-4C1D-8547-B5459DB72D69@example.org>
From: Edd Dumbill <edd@example.org>
To: Edd Dumbill <edd@example.org>
Content-Type: text/plain; charset=US-ASCII; format=flowed
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0 (Apple Message framework v928.1)
Subject: Score
Date: Wed, 6 Aug 2012 04:32:54 -0700
X-Mailer: Apple Mail (2.928.1)
Status: RO
Content-Length: 56
Lines: 7

Student: 1
GPA: 3.34